name: awogen
description: classes and collections generator for appwrite.io sdks
version: 0.9.9
homepage: https://github.com/devloic/awogen

environment:
  sdk: '>=3.0.0 <4.0.0'
 
#Packages used in lib/ must be declared in the `dependencies` section.

dependencies:  
  cupertino_icons: ^1.0.2
  appwrite: ^9.0.0
  chalkdart: ^2.0.9
  dart_appwrite: ^8.0.0
  email_validator: ^2.1.17
  intl: ^0.18.1
  awogen_annotations: ^0.9.2
  envied_generator: ^0.3.0+3
  awogen_generator: ^0.9.7

dev_dependencies:
  lints: ^2.0.0
  source_gen: ^1.3.2

 