name: awogen_generator
description: build_runner generator for awogen
version: 0.9.7
homepage: https://github.com/devloic/awogen

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  dart_appwrite: ^8.0.0
  analyzer: ^5.13.0
  build: ^2.4.0
  source_gen:  ^1.3.2
  awogen: ^0.9.8
  envied: ^0.3.0+3
  envied_generator: ^0.3.0+3
  flutter_dotenv: ^5.0.2
  chalkdart: ^2.0.9

dev_dependencies:
  build_runner: ^2.3.3
  lints: 
