name: awogen_annotations
description: build_runner annotation for awogen
version: 0.9.2
homepage: https://github.com/devloic/awogen

environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
